// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type AccountancyAccountInvolvedAccounts struct {
}

type AccountancyAccountInvolvedAccountsDeleteResponse struct {
}

type AccountancyAccountInvolvedAccountsGetResponse struct {
}

type AccountancyAccountInvolvedAccountsPostResponse struct {
}

type AccountancyAccountInvolvedAccountsPutResponse struct {
}

type AccountancyAccountOwners struct {
}

type AccountancyAccountOwnersDeleteResponse struct {
}

type AccountancyAccountOwnersGetResponse struct {
}

type AccountancyAccountOwnersPostResponse struct {
}

type AccountancyAccountOwnersPutResponse struct {
}

type AccountancyClientGroups struct {
}

type AccountancyClientGroupsGetResponse struct {
}

type AccountancyClientMainGroups struct {
}

type AccountancyClientMainGroupsGetResponse struct {
}

type AccountancyInvolvedUserRoles struct {
}

type AccountancyInvolvedUserRolesDeleteResponse struct {
}

type AccountancyInvolvedUserRolesGetResponse struct {
}

type AccountancyInvolvedUserRolesPostResponse struct {
}

type AccountancyInvolvedUserRolesPutResponse struct {
}

type AccountancyInvolvedUsers struct {
}

type AccountancyInvolvedUsersDeleteResponse struct {
}

type AccountancyInvolvedUsersGetResponse struct {
}

type AccountancyInvolvedUsersPostResponse struct {
}

type AccountancyInvolvedUsersPutResponse struct {
}

type AccountancySolutionLinks struct {
}

type AccountancySolutionLinksDeleteResponse struct {
}

type AccountancySolutionLinksGetResponse struct {
}

type AccountancySolutionLinksPostResponse struct {
}

type AccountancySolutionLinksPutResponse struct {
}

type AccountancyTaskTypes struct {
}

type AccountancyTaskTypesDeleteResponse struct {
}

type AccountancyTaskTypesGetResponse struct {
}

type AccountancyTaskTypesPostResponse struct {
}

type AccountancyTaskTypesPutResponse struct {
}
