// Copyright 2026 Pimmetjeoss and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type AccountancyAccountInvolvedAccounts struct {
}

type AccountancyAccountOwners struct {
}

type AccountancyClientGroups struct {
}

type AccountancyClientMainGroups struct {
}

type AccountancyInvolvedUserRoles struct {
}

type AccountancyInvolvedUsers struct {
}

type AccountancySolutionLinks struct {
}

type AccountancyTaskTypes struct {
}
