// Copyright 2026 Pimmetjeoss and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"exact-online-accountancy-pp-cli/internal/cli"
	"exact-online-accountancy-pp-cli/internal/client"
	"exact-online-accountancy-pp-cli/internal/cliutil"
	"exact-online-accountancy-pp-cli/internal/config"
	"exact-online-accountancy-pp-cli/internal/learn"
	"exact-online-accountancy-pp-cli/internal/mcp/bound"
	"exact-online-accountancy-pp-cli/internal/mcp/cobratree"
	"exact-online-accountancy-pp-cli/internal/platform"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	s.AddTool(
		mcplib.NewTool("accountancy_account-involved-accounts-delete",
			mcplib.WithDescription("This resource will show all accounts which are involved for a specific account and will also show the type of the relation between the accounts. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountInvolvedAccounts Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyAccountInvolvedAccountsDeleteResponse. Destructive."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/AccountInvolvedAccounts", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-involved-accounts-get",
			mcplib.WithDescription("This resource will show all accounts which are involved for a specific account and will also show the type of the relation between the accounts. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountInvolvedAccounts Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyAccountInvolvedAccountsGetResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/AccountInvolvedAccounts", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-involved-accounts-post",
			mcplib.WithDescription("This resource will show all accounts which are involved for a specific account and will also show the type of the relation between the accounts. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountInvolvedAccounts Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyAccountInvolvedAccountsPostResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/AccountInvolvedAccounts", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-involved-accounts-put",
			mcplib.WithDescription("This resource will show all accounts which are involved for a specific account and will also show the type of the relation between the accounts. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountInvolvedAccounts Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyAccountInvolvedAccountsPutResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/AccountInvolvedAccounts", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-owners-delete",
			mcplib.WithDescription("The account owners are accounts which represents the owners or shareholders for a specific account. In this resource also the percentage of shares which the account holds are stored. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountOwners Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyAccountOwnersDeleteResponse. Destructive."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/AccountOwners", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-owners-get",
			mcplib.WithDescription("The account owners are accounts which represents the owners or shareholders for a specific account. In this resource also the percentage of shares which the account holds are stored. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountOwners Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyAccountOwnersGetResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/AccountOwners", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-owners-post",
			mcplib.WithDescription("The account owners are accounts which represents the owners or shareholders for a specific account. In this resource also the percentage of shares which the account holds are stored. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountOwners Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyAccountOwnersPostResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/AccountOwners", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-owners-put",
			mcplib.WithDescription("The account owners are accounts which represents the owners or shareholders for a specific account. In this resource also the percentage of shares which the account holds are stored. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountOwners Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyAccountOwnersPutResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/AccountOwners", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_client-groups-get",
			mcplib.WithDescription("The client groups are used to classify the clients. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyClientGroups Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyClientGroupsGetResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/ClientGroups", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_client-main-groups-get",
			mcplib.WithDescription("The client main groups are used to classify the client groups. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyClientMainGroups Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyClientMainGroupsGetResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/ClientMainGroups", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-user-roles-delete",
			mcplib.WithDescription("An involved user role represents a role which a user can have in an accountancy firm. This involved user role can be used to indicate the role that a user have for a certain client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUserRoles Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyInvolvedUserRolesDeleteResponse. Destructive."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/InvolvedUserRoles", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-user-roles-get",
			mcplib.WithDescription("An involved user role represents a role which a user can have in an accountancy firm. This involved user role can be used to indicate the role that a user have for a certain client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUserRoles Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyInvolvedUserRolesGetResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/InvolvedUserRoles", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-user-roles-post",
			mcplib.WithDescription("An involved user role represents a role which a user can have in an accountancy firm. This involved user role can be used to indicate the role that a user have for a certain client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUserRoles Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyInvolvedUserRolesPostResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/InvolvedUserRoles", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-user-roles-put",
			mcplib.WithDescription("An involved user role represents a role which a user can have in an accountancy firm. This involved user role can be used to indicate the role that a user have for a certain client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUserRoles Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyInvolvedUserRolesPutResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/InvolvedUserRoles", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-users-delete",
			mcplib.WithDescription("The involved users keeps track on all users which are involved for a certain client of the accountant. The involved user also shows the role that the user has for the involved client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyInvolvedUsersDeleteResponse. Destructive."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/InvolvedUsers", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-users-get",
			mcplib.WithDescription("The involved users keeps track on all users which are involved for a certain client of the accountant. The involved user also shows the role that the user has for the involved client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyInvolvedUsersGetResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/InvolvedUsers", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-users-post",
			mcplib.WithDescription("The involved users keeps track on all users which are involved for a certain client of the accountant. The involved user also shows the role that the user has for the involved client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyInvolvedUsersPostResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/InvolvedUsers", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-users-put",
			mcplib.WithDescription("The involved users keeps track on all users which are involved for a certain client of the accountant. The involved user also shows the role that the user has for the involved client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyInvolvedUsersPutResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/InvolvedUsers", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_solution-links-delete",
			mcplib.WithDescription("Solution links are used to store which bookkeeping solution is used for a certain account. This can be the bookkeeping solution of Exact Online which is mentioned as ‘internal’ or a bookkeeping solution of another vender which is mentioned as ‘external’. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancySolutionLinks Scope: Accountancy practicemanagement. Required: division. Returns the AccountancySolutionLinksDeleteResponse. Destructive."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/SolutionLinks", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_solution-links-get",
			mcplib.WithDescription("Solution links are used to store which bookkeeping solution is used for a certain account. This can be the bookkeeping solution of Exact Online which is mentioned as ‘internal’ or a bookkeeping solution of another vender which is mentioned as ‘external’. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancySolutionLinks Scope: Accountancy practicemanagement. Required: division. Returns the AccountancySolutionLinksGetResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/SolutionLinks", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_solution-links-post",
			mcplib.WithDescription("Solution links are used to store which bookkeeping solution is used for a certain account. This can be the bookkeeping solution of Exact Online which is mentioned as ‘internal’ or a bookkeeping solution of another vender which is mentioned as ‘external’. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancySolutionLinks Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancySolutionLinksPostResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/SolutionLinks", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_solution-links-put",
			mcplib.WithDescription("Solution links are used to store which bookkeeping solution is used for a certain account. This can be the bookkeeping solution of Exact Online which is mentioned as ‘internal’ or a bookkeeping solution of another vender which is mentioned as ‘external’. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancySolutionLinks Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancySolutionLinksPutResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/SolutionLinks", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_task-types-delete",
			mcplib.WithDescription("The task types are specific types defined by the user of the accountancy firm.This resource shows the custom types defined within a company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyTaskTypes Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyTaskTypesDeleteResponse. Destructive."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/TaskTypes", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_task-types-get",
			mcplib.WithDescription("The task types are specific types defined by the user of the accountancy firm.This resource shows the custom types defined within a company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyTaskTypes Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyTaskTypesGetResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/TaskTypes", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_task-types-post",
			mcplib.WithDescription("The task types are specific types defined by the user of the accountancy firm.This resource shows the custom types defined within a company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyTaskTypes Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyTaskTypesPostResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/TaskTypes", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_task-types-put",
			mcplib.WithDescription("The task types are specific types defined by the user of the accountancy firm.This resource shows the custom types defined within a company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyTaskTypes Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyTaskTypesPutResponse."),
			mcplib.WithNumber("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/TaskTypes", false, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcpToolError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Run 'exact-online-accountancy-pp-cli auth login' to re-authenticate." +
					"\n      Run 'exact-online-accountancy-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Run 'exact-online-accountancy-pp-cli auth login' to re-authenticate." +
					"\n      Run 'exact-online-accountancy-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Run 'exact-online-accountancy-pp-cli auth login' to re-authenticate." +
					"\n      Run 'exact-online-accountancy-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	c := newMCPClientFromConfig(cfg)
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	return c, session, nil
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(cfg *config.Config) *client.Client {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "exact-online-accountancy",
		"description": "Accountancy-only Exact Online REST/OData API surface generated from the official Exact Online REST API documentation.",
		"archetype":   "crm",
		"tool_count":  26,
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion exact-online-accountancy-pp-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "EXACT_ONLINE_ACCOUNTANCY_OAUTH2",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "accountancy",
				"description": "Manage accountancy",
				"endpoints":   []string{"account-involved-accounts-delete", "account-involved-accounts-get", "account-involved-accounts-post", "account-involved-accounts-put", "account-owners-delete", "account-owners-get", "account-owners-post", "account-owners-put", "client-groups-get", "client-main-groups-get", "involved-user-roles-delete", "involved-user-roles-get", "involved-user-roles-post", "involved-user-roles-put", "involved-users-delete", "involved-users-get", "involved-users-post", "involved-users-put", "solution-links-delete", "solution-links-get", "solution-links-post", "solution-links-put", "task-types-delete", "task-types-get", "task-types-post", "task-types-put"},
				"writable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
		"playbook": []map[string]string{
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
