// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"exact-online-accountancy-pp-cli/internal/cli"
	"exact-online-accountancy-pp-cli/internal/client"
	"exact-online-accountancy-pp-cli/internal/cliutil"
	"exact-online-accountancy-pp-cli/internal/config"
	"exact-online-accountancy-pp-cli/internal/mcp/cobratree"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("accountancy_account-involved-accounts-delete",
			mcplib.WithDescription("This resource will show all accounts which are involved for a specific account and will also show the type of the relation between the accounts. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountInvolvedAccounts Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyAccountInvolvedAccountsDeleteResponse. Destructive."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/AccountInvolvedAccounts", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-involved-accounts-get",
			mcplib.WithDescription("This resource will show all accounts which are involved for a specific account and will also show the type of the relation between the accounts. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountInvolvedAccounts Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyAccountInvolvedAccountsGetResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/AccountInvolvedAccounts", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-involved-accounts-post",
			mcplib.WithDescription("This resource will show all accounts which are involved for a specific account and will also show the type of the relation between the accounts. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountInvolvedAccounts Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyAccountInvolvedAccountsPostResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/AccountInvolvedAccounts", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-involved-accounts-put",
			mcplib.WithDescription("This resource will show all accounts which are involved for a specific account and will also show the type of the relation between the accounts. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountInvolvedAccounts Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyAccountInvolvedAccountsPutResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/AccountInvolvedAccounts", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-owners-delete",
			mcplib.WithDescription("The account owners are accounts which represents the owners or shareholders for a specific account. In this resource also the percentage of shares which the account holds are stored. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountOwners Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyAccountOwnersDeleteResponse. Destructive."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/AccountOwners", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-owners-get",
			mcplib.WithDescription("The account owners are accounts which represents the owners or shareholders for a specific account. In this resource also the percentage of shares which the account holds are stored. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountOwners Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyAccountOwnersGetResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/AccountOwners", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-owners-post",
			mcplib.WithDescription("The account owners are accounts which represents the owners or shareholders for a specific account. In this resource also the percentage of shares which the account holds are stored. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountOwners Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyAccountOwnersPostResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/AccountOwners", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_account-owners-put",
			mcplib.WithDescription("The account owners are accounts which represents the owners or shareholders for a specific account. In this resource also the percentage of shares which the account holds are stored. This functionality is only available in a practice management company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyAccountOwners Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyAccountOwnersPutResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/AccountOwners", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_client-groups-get",
			mcplib.WithDescription("The client groups are used to classify the clients. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyClientGroups Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyClientGroupsGetResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/ClientGroups", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_client-main-groups-get",
			mcplib.WithDescription("The client main groups are used to classify the client groups. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyClientMainGroups Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyClientMainGroupsGetResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/ClientMainGroups", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-user-roles-delete",
			mcplib.WithDescription("An involved user role represents a role which a user can have in an accountancy firm. This involved user role can be used to indicate the role that a user have for a certain client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUserRoles Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyInvolvedUserRolesDeleteResponse. Destructive."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/InvolvedUserRoles", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-user-roles-get",
			mcplib.WithDescription("An involved user role represents a role which a user can have in an accountancy firm. This involved user role can be used to indicate the role that a user have for a certain client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUserRoles Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyInvolvedUserRolesGetResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/InvolvedUserRoles", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-user-roles-post",
			mcplib.WithDescription("An involved user role represents a role which a user can have in an accountancy firm. This involved user role can be used to indicate the role that a user have for a certain client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUserRoles Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyInvolvedUserRolesPostResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/InvolvedUserRoles", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-user-roles-put",
			mcplib.WithDescription("An involved user role represents a role which a user can have in an accountancy firm. This involved user role can be used to indicate the role that a user have for a certain client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUserRoles Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyInvolvedUserRolesPutResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/InvolvedUserRoles", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-users-delete",
			mcplib.WithDescription("The involved users keeps track on all users which are involved for a certain client of the accountant. The involved user also shows the role that the user has for the involved client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyInvolvedUsersDeleteResponse. Destructive."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/InvolvedUsers", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-users-get",
			mcplib.WithDescription("The involved users keeps track on all users which are involved for a certain client of the accountant. The involved user also shows the role that the user has for the involved client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyInvolvedUsersGetResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/InvolvedUsers", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-users-post",
			mcplib.WithDescription("The involved users keeps track on all users which are involved for a certain client of the accountant. The involved user also shows the role that the user has for the involved client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyInvolvedUsersPostResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/InvolvedUsers", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_involved-users-put",
			mcplib.WithDescription("The involved users keeps track on all users which are involved for a certain client of the accountant. The involved user also shows the role that the user has for the involved client. This functionality is only available in a practice company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyInvolvedUsersPutResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/InvolvedUsers", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_solution-links-delete",
			mcplib.WithDescription("Solution links are used to store which bookkeeping solution is used for a certain account. This can be the bookkeeping solution of Exact Online which is mentioned as ‘internal’ or a bookkeeping solution of another vender which is mentioned as ‘external’. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancySolutionLinks Scope: Accountancy practicemanagement. Required: division. Returns the AccountancySolutionLinksDeleteResponse. Destructive."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/SolutionLinks", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_solution-links-get",
			mcplib.WithDescription("Solution links are used to store which bookkeeping solution is used for a certain account. This can be the bookkeeping solution of Exact Online which is mentioned as ‘internal’ or a bookkeeping solution of another vender which is mentioned as ‘external’. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancySolutionLinks Scope: Accountancy practicemanagement. Required: division. Returns the AccountancySolutionLinksGetResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/SolutionLinks", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_solution-links-post",
			mcplib.WithDescription("Solution links are used to store which bookkeeping solution is used for a certain account. This can be the bookkeeping solution of Exact Online which is mentioned as ‘internal’ or a bookkeeping solution of another vender which is mentioned as ‘external’. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancySolutionLinks Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancySolutionLinksPostResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/SolutionLinks", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_solution-links-put",
			mcplib.WithDescription("Solution links are used to store which bookkeeping solution is used for a certain account. This can be the bookkeeping solution of Exact Online which is mentioned as ‘internal’ or a bookkeeping solution of another vender which is mentioned as ‘external’. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancySolutionLinks Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancySolutionLinksPutResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/SolutionLinks", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_task-types-delete",
			mcplib.WithDescription("The task types are specific types defined by the user of the accountancy firm.This resource shows the custom types defined within a company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyTaskTypes Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyTaskTypesDeleteResponse. Destructive."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/v1/{division}/accountancy/TaskTypes", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_task-types-get",
			mcplib.WithDescription("The task types are specific types defined by the user of the accountancy firm.This resource shows the custom types defined within a company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyTaskTypes Scope: Accountancy practicemanagement. Required: division. Returns the AccountancyTaskTypesGetResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v1/{division}/accountancy/TaskTypes", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_task-types-post",
			mcplib.WithDescription("The task types are specific types defined by the user of the accountancy firm.This resource shows the custom types defined within a company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyTaskTypes Scope: Accountancy practicemanagement. Required: division. Returns the new AccountancyTaskTypesPostResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v1/{division}/accountancy/TaskTypes", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)
	s.AddTool(
		mcplib.NewTool("accountancy_task-types-put",
			mcplib.WithDescription("The task types are specific types defined by the user of the accountancy firm.This resource shows the custom types defined within a company. Official docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyTaskTypes Scope: Accountancy practicemanagement. Required: division. Returns the updated AccountancyTaskTypesPutResponse."),
			mcplib.WithString("division", mcplib.Required(), mcplib.Description("Exact Online division code.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/api/v1/{division}/accountancy/TaskTypes", []mcpParamBinding{{PublicName: "division", WireName: "division", Location: "path"}}, []string{"division"}),
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export EXACT_ONLINE_ACCOUNTANCY_OAUTH2=<your-key>" +
					"\n      Run 'exact-online-accountancy-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export EXACT_ONLINE_ACCOUNTANCY_OAUTH2=<your-key>" +
					"\n      Run 'exact-online-accountancy-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export EXACT_ONLINE_ACCOUNTANCY_OAUTH2=<your-key>" +
					"\n      Run 'exact-online-accountancy-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "exact-online-accountancy-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "exact-online-accountancy-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "exact-online-accountancy",
		"description": "Accountancy-only Exact Online REST/OData API surface generated from the official Exact Online REST API...",
		"archetype":   "crm",
		"tool_count":  26,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion exact-online-accountancy-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "EXACT_ONLINE_ACCOUNTANCY_OAUTH2",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "accountancy",
				"description": "Manage accountancy",
				"endpoints":   []string{"account-involved-accounts-delete", "account-involved-accounts-get", "account-involved-accounts-post", "account-involved-accounts-put", "account-owners-delete", "account-owners-get", "account-owners-post", "account-owners-put", "client-groups-get", "client-main-groups-get", "involved-user-roles-delete", "involved-user-roles-get", "involved-user-roles-post", "involved-user-roles-put", "involved-users-delete", "involved-users-get", "involved-users-post", "involved-users-put", "solution-links-delete", "solution-links-get", "solution-links-post", "solution-links-put", "task-types-delete", "task-types-get", "task-types-post", "task-types-put"},
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
		"playbook": []map[string]string{
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
