// Copyright 2026 Pimmetjeoss and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountancyCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "accountancy",
		Short:       "Accountancy-only Exact Online REST/OData API surface generated from the official Exact Online REST API documentation.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountancyAccountInvolvedAccountsDeleteCmd(flags))
	cmd.AddCommand(newAccountancyAccountInvolvedAccountsGetCmd(flags))
	cmd.AddCommand(newAccountancyAccountInvolvedAccountsPostCmd(flags))
	cmd.AddCommand(newAccountancyAccountInvolvedAccountsPutCmd(flags))
	cmd.AddCommand(newAccountancyAccountOwnersDeleteCmd(flags))
	cmd.AddCommand(newAccountancyAccountOwnersGetCmd(flags))
	cmd.AddCommand(newAccountancyAccountOwnersPostCmd(flags))
	cmd.AddCommand(newAccountancyAccountOwnersPutCmd(flags))
	cmd.AddCommand(newAccountancyClientGroupsGetCmd(flags))
	cmd.AddCommand(newAccountancyClientMainGroupsGetCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUserRolesDeleteCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUserRolesGetCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUserRolesPostCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUserRolesPutCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUsersDeleteCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUsersGetCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUsersPostCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUsersPutCmd(flags))
	cmd.AddCommand(newAccountancySolutionLinksDeleteCmd(flags))
	cmd.AddCommand(newAccountancySolutionLinksGetCmd(flags))
	cmd.AddCommand(newAccountancySolutionLinksPostCmd(flags))
	cmd.AddCommand(newAccountancySolutionLinksPutCmd(flags))
	cmd.AddCommand(newAccountancyTaskTypesDeleteCmd(flags))
	cmd.AddCommand(newAccountancyTaskTypesGetCmd(flags))
	cmd.AddCommand(newAccountancyTaskTypesPostCmd(flags))
	cmd.AddCommand(newAccountancyTaskTypesPutCmd(flags))
	return cmd
}
