// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountancyCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "accountancy",
		Short: "Manage accountancy",
	}

	cmd.AddCommand(newAccountancyAccountInvolvedAccountsDeleteCmd(flags))
	cmd.AddCommand(newAccountancyAccountInvolvedAccountsGetCmd(flags))
	cmd.AddCommand(newAccountancyAccountInvolvedAccountsPostCmd(flags))
	cmd.AddCommand(newAccountancyAccountInvolvedAccountsPutCmd(flags))
	cmd.AddCommand(newAccountancyAccountOwnersDeleteCmd(flags))
	cmd.AddCommand(newAccountancyAccountOwnersGetCmd(flags))
	cmd.AddCommand(newAccountancyAccountOwnersPostCmd(flags))
	cmd.AddCommand(newAccountancyAccountOwnersPutCmd(flags))
	cmd.AddCommand(newAccountancyClientGroupsGetCmd(flags))
	cmd.AddCommand(newAccountancyClientMainGroupsGetCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUserRolesDeleteCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUserRolesGetCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUserRolesPostCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUserRolesPutCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUsersDeleteCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUsersGetCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUsersPostCmd(flags))
	cmd.AddCommand(newAccountancyInvolvedUsersPutCmd(flags))
	cmd.AddCommand(newAccountancySolutionLinksDeleteCmd(flags))
	cmd.AddCommand(newAccountancySolutionLinksGetCmd(flags))
	cmd.AddCommand(newAccountancySolutionLinksPostCmd(flags))
	cmd.AddCommand(newAccountancySolutionLinksPutCmd(flags))
	cmd.AddCommand(newAccountancyTaskTypesDeleteCmd(flags))
	cmd.AddCommand(newAccountancyTaskTypesGetCmd(flags))
	cmd.AddCommand(newAccountancyTaskTypesPostCmd(flags))
	cmd.AddCommand(newAccountancyTaskTypesPutCmd(flags))
	cmd.AddCommand(newAccountancyResourcesCmd(flags))
	cmd.AddCommand(newAccountancyDocsCmd(flags))
	cmd.AddCommand(newAccountancyPracticeSetupCmd(flags))
	cmd.AddCommand(newAccountancyClientSnapshotCmd(flags))
	cmd.AddCommand(newAccountancyOwnershipMapCmd(flags))
	return cmd
}
