// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAccountancyAccountOwnersGetCmd(flags *rootFlags) *cobra.Command {
	var q accountancyODataFlags

	cmd := &cobra.Command{
		Use:         "account-owners-get <division>",
		Short:       "The account owners are accounts which represents the owners or shareholders for a specific account. In this resource...",
		Example:     "  exact-online-accountancy-pp-cli accountancy account-owners-get 42",
		Annotations: map[string]string{"pp:endpoint": "accountancy.account-owners-get", "pp:method": "GET", "pp:path": "/api/v1/{division}/accountancy/AccountOwners", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/{division}/accountancy/AccountOwners"
			path = replacePathParam(path, "division", args[0])
			params := q.toParams()
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}

	addAccountancyODataFlags(cmd, &q)

	return cmd
}
